In [1]:
import torch

In [2]:
x = torch.rand(5,3)

In [3]:
x

tensor([[0.4751, 0.0345, 0.5882],
        [0.0399, 0.3332, 0.7128],
        [0.4248, 0.5243, 0.2394],
        [0.6628, 0.8616, 0.8588],
        [0.9483, 0.0610, 0.7506]])

In [4]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [5]:
b=a.numpy()

In [6]:
print(b)

[1. 1. 1. 1. 1.]


In [7]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [8]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [9]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [10]:
# 当GPU可用时,我们可以运行以下代码
# 我们将使用`torch.device`来将tensor移入和移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建tensor
    x = x.to(device)                       # 或者使用`.to("cuda")`方法
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # `.to`也能在移动时改变dtype

tensor([[1.4751, 1.0345, 1.5882],
        [1.0399, 1.3332, 1.7128],
        [1.4248, 1.5243, 1.2394],
        [1.6628, 1.8616, 1.8588],
        [1.9483, 1.0610, 1.7506]], device='cuda:0')
tensor([[1.4751, 1.0345, 1.5882],
        [1.0399, 1.3332, 1.7128],
        [1.4248, 1.5243, 1.2394],
        [1.6628, 1.8616, 1.8588],
        [1.9483, 1.0610, 1.7506]], dtype=torch.float64)


In [11]:
print(torch.cuda.is_available())

True


In [12]:
a = torch.Tensor(5,3)

In [13]:
a = a.cuda()

In [14]:
a

tensor([[-4.3856e-36,  9.4868e-43, -4.3856e-36],
        [ 9.4868e-43, -4.3856e-36,  9.4868e-43],
        [-4.3856e-36,  9.4868e-43, -4.3856e-36],
        [ 9.4868e-43, -4.3856e-36,  9.4868e-43],
        [-4.3856e-36,  9.4868e-43, -4.3856e-36]], device='cuda:0')